### ISSUE TITLE
[QUESTION] Is there a way to substitute default answer_with_facts.txt prompt

### ISSUE THREAD

**Issue by cz35iek** [microsoft/kernel-memory#110]
Hey guys!

I'm wondering if there is a way to substitute default Completion API prompt to my custom one? Or maybe I can somehow inject my custom SearchClient that would also solve my issue.

Kind regards,
Dawid

**Comment by anthonypuppo** [comment]
https://github.com/microsoft/kernel-memory/blob/b275662fdb6d5429f674d0ac8d9fb753054ef000/dotnet/CoreLib/MemoryStorage/AzureCognitiveSearch/AzureCognitiveSearchMemory.cs#L574-L581

As there's no conditions it builds a string of "()". Obviously an invalid OData filter, so the call to ACS fails. It should check whether there's any conditions in the filter and, only then, append to the conditions list.

I'll can create a PR to fix this in a bit unless someone gets to it first.

**Comment by luismanez** [comment]
Pretty sure currently there is no way to substitute the Prompt txt file (also interested here and inspect the source code). 

The SearchClient has a ITextGeneration interface that is the one makes the request to OpenAI. See if you can use this method when building the MemoryClient.

```csharp
public MemoryClientBuilder WithCustomTextGeneration(ITextGeneration service)
    {
        service = service ?? throw new ConfigurationException("The text generator instance is NULL");
        this.AddSingleton<ITextGeneration>(service);
        return this;
    }
```

**Comment by dluc** [comment]
The feature is on the roadmap, thanks for raising visibility :-)

**Comment by lecramr** [comment]
That would be a really great addition!

**Comment by lecramr** [comment]
I have created a PR with my suggestions, but I am a little unsure about the implementation in the "KernelMemoryBuilder.cs" class.

**Comment by dluc** [comment]
@lecramr I like the approach, I'll take a look and make some changes, e.g. renaming to something less generic (because in future the could be many more prompts).  On a different note, another option would be passing the prompt during the request, so one could experiment with different prompts without changing the configuration.

**Comment by lecramr** [comment]
Great! Sure, go ahead 🙂.
That would also be a very useful approach, although experimenting could also be done with a PromptSupplier with more dynamic parameters, maybe it would make sense for the PromptSupplier to not only pass the "fileName" or "promptName" but also let it handle the replacement of the (maybe dynamic?) tokens supplied. So to pass a Dictionary with (("{{$facts}}", suppliedFacts), ("{{$input}}", "Supplied input")), so that the implementation could dynamically react based on supplied facts and/or input. So the method signature would be something like "string ReadPrompt(string promptName, Dictionary<string, string> replacementTokens);".

**Comment by dluc** [comment]
sending my changes in a couple of mins :-)
