### ISSUE TITLE
[Question] Since last version, I cannot use the FromConfiguration anymore

### ISSUE THREAD

**Issue by MaxenceBoucquez** [microsoft/kernel-memory#283]
### Context / Scenario

In my project, I was using the KernelMemoryBuilder.FromConfiguration extension method, but after a package update I can't do it anymore. 
I saw the method has been reduced and is now present in the package named "Microsoft.KernelMemory.Service". The thing is I can't find the nuget package for my project so I can't use the method anymore.

### Question

What can I do so I can use the method again?

**Comment by dluc** [comment]
hi @MaxenceBoucquez that's correct, since the method depends on packages that are used only by the Service project (like Redis, Elasticsearch, and other will be added over time), the code for that method is hosted in the Service project, which is not released as a nuget. The current recommendation is taking a copy of the code, it's 1 or 2 files at most.
