### ISSUE TITLE
[Question] It seems that embedding are not used

### ISSUE THREAD

**Issue by alkampfergit** [microsoft/kernel-memory#300]
### Context / Scenario

In a minimal example project to test MongoDb atlas vector store, it seems that withEmbeddings is always false.

### Question

I'm developing the storage (standard and vector) for mongodb atlas https://github.com/alkampfergit/kernel-memory/tree/feature/first-atlas-support I've implemented a first version but I still not implemented the vector part, now I searched in source code for unit test to verify search with embedding but I did not find anything.

My code will throw exception if withEmbeddings is true, now I've used in a minmal console application and I'm able to query the pdf document, without any error. This means that when I call AskAsync no embedding is used. 

What could I've missed in configuration?

![image](https://github.com/microsoft/kernel-memory/assets/358545/4bf3e372-6584-4ad3-b78c-5f987b37a7d4)

**Comment by dluc** [comment]
`withEmbeddings` is used by a client asking to return MemoryRecords including the vector data. 

Currently, KM never uses that feature, using only other MemoryRecord properties. 

However, since it's a public API, one might want to load those records having also the embedding vector included, e.g. to copy data somewhere else, to work directly with vector data, etc.

If you do a global search of `withEmbeddings: true` you will find a few tests using that argument, e.g. to compare cosine similarity across different storage solutions and to assert the cosine similarity value precision.
