### ISSUE TITLE
[Feature Request] Should line endings be removed by decoders?

### ISSUE THREAD

**Issue by marcominerva** [microsoft/kernel-memory#375]
### Context / Scenario

While trying to understand different relevance values from different embedding models, I have noticed that I get more relevant results if the text is pre-processed by the encoders, for example removing line endings.

### The problem

I would like to understand if pre-processing of documents can effectively lead to better results.

### Proposed solution

For example, in case of [PdfDecoder](https://github.com/microsoft/kernel-memory/blob/main/service/Core/DataFormats/Pdf/PdfDecoder.cs#L26), I have tried something like this:

```csharp
public FileContent ExtractContent(Stream data)
{
    var result = new FileContent();

    using PdfDocument? pdfDocument = PdfDocument.Open(data);
    if (pdfDocument == null) { return result; }

    var options = new ContentOrderTextExtractor.Options
    {
        ReplaceWhitespaceWithSpace = true,
        SeparateParagraphsWithDoubleNewline = false,
    };

    foreach (Page? page in pdfDocument.GetPages().Where(x => x != null))
    {
        string pageContent = (ContentOrderTextExtractor.GetText(page, options) ?? string.Empty).ReplaceLineEndings(" ");
        result.Sections.Add(new FileSection(page.Number, pageContent, false));
    }

    return result;
}
```

Using `options` and calling `ReplaceLineEndings`, of course chunks change, but in this way each of them is "cleaner", so it seems that this could produce better result. 

However, I'm wondering if this idea is correct.

### Importance

None

**Comment by dluc** [comment]
Removing line endings is a tricky step because it affects the semantics. From a high level perspective I usually leave all the line endings in place, until the moment of calculating embeddings and saving the text chunk. I would avoid removing line endings while chunking sentences because it might join paragraphs together. Then there's the scenario where one might want to use "the chunk before" and "the chunk after", merged with the current chunk. In this case it would be better having the original line endings.

I'm a bit surprised that cosine similarity is affected so much by this detail to be honest, and I would not jump the gun without a thorough investigation with a considerable amount of test cases and a report comparing results. I'm worried we could make things worse overall. 

There's also another way to look at it if you want: for each pieace of text we could have multiple versions (with line endings, without, etc), and calculate embeddings for all. It would increase cost, but could make things better for everyone.

**Comment by marcominerva** [comment]
I understand your point, so I think that the correct approach could be the feature I have discussed in https://github.com/microsoft/kernel-memory/issues/379, so everyone can makes the tests for a specific use case.

**Comment by marcominerva** [comment]
Now that https://github.com/microsoft/kernel-memory/issues/379 has been shipped, this scenario can be fully covered.
