### ISSUE TITLE
[Bug] Inconsistent chunk ID for repeated uploads leads to duplicate entries in vector store

### ISSUE THREAD

**Issue by fvd2** [microsoft/kernel-memory#385]
### Context / Scenario

**Context**
- I am developing a RAG application that allows users to generate a summary with citations of meeting notes from a CRM system. 
- I use Kernel Memory to import and search documents
- When users request a summary, the selected meeting notes are retrieved from a database and imported using the ImportTextAsync method. Then a search is performed using the SearchAsync method

**Issue** 
I get duplicate entries in my vector database (Azure AI Search) when a meeting note is imported multiple times, because the generated ID is not consistent for repeated uploads of the same document. The meeting note then shows up multiple times in the search results, which leads to multiple citations for the document and takes up the limited number of matches (defined by MaxMatchesCount) 

**Analysis**
It appears the partition ID is a Guid that is generated by the pipeline. 
![image](https://github.com/microsoft/kernel-memory/assets/68645334/eda2b879-ebd3-42d2-82fb-72cd4d88feac)
![image](https://github.com/microsoft/kernel-memory/assets/68645334/1e71cbc5-1a04-4463-b61a-9e90c3d5500b)

**Potential solution**
Use a hash of the document contents instead of a new Guid for the partition ID. While debugging I tested a simple workaround by passing the ContentSHA256 property in the embeddingFileNameDetails in my CustomGenerateEmbeddingsHandler (otherwise it is an empty string) and then using it instead of the Guid in my CustomSaveRecordsHandler. 
![image](https://github.com/microsoft/kernel-memory/assets/68645334/bc45df57-0aae-465d-a10d-af9a01d21426)

### What happened?

I expect the partition ID and therefore the document ID used in Azure AI Search to be consistent across repeated uploads of the same document, resulting in no duplicate entries. 

### Importance

a fix would make my life easier

### Platform, Language, Versions

C#
Microsoft.KernelMemory.Core version 0.27.240205.2
.NET 8

**Comment by 0x7c13** [comment]
Did you supply a documentId when ingesting the meeting notes? If not, can you use the meeting name as the documentId and try import it multiple times to see if the same issue occurs?

**Comment by dluc** [comment]
When uploading the same document multiple times, if you provide the same Document ID (see also previous comment) the previous records will be deleted and new ones will be created. The logic is in `SaveRecordsHandler.DeletePreviousRecordsAsync()`.

Unique hashes are not sufficient because files length can change, and the resulting number of partitions can change, so there's always a need to remove previous records, which is the approach used by `SaveRecordsHandler`.

Hashing the document content would cause also other problems, because it's actually allowed to upload the same files multiple times, under a different Document ID.

I would suggest using a consistent Document ID first, and if you still see duplication, check why `SaveRecordsHandler` is not deleting the old records (see `DeletePreviousRecordsAsync` method).
