### ISSUE TITLE
Clearly define public API and differentiate internal contracts

### ISSUE THREAD

**Issue by crickman** [microsoft/kernel-memory#45]
As part of the transition from preview to production, it may make sense to reduce public surface area.  Even though this is an open source project, people taking dependencies (for whatever reason) on internal contracts that are incorrectly scoped will not be delighted as changes progress.

**Goal: Scope classes that do not have `public `intent as `internal`:**

Example: AzureCognitiveSearchMemoryRecord  - https://github.com/microsoft/semantic-kernel/issues/2678

**Comment by dluc** [comment]
FWIW the public API is defined by https://github.com/microsoft/semantic-memory/blob/main/dotnet/ClientLib/ISemanticMemoryClient.cs

The intention is to offer SM as a Service and a Plugin. The service already follows the interface above, so it's very easy to discover what is possible to do with SM.

From a coding perspective, many more classes are public only for the purpose of extending the project, e.g. adding new handlers, and for those rare circumstances where one wants to embed SM using the serverless client. Over time I think the serverless client will be phased out, because it won't allow leveraging multiple languages, and it won't be able to offer some of the new APIs.

I'm sure there are a few "public" artifacts which could be turned to "internal", although that seems to be a problem only for projects using the embedded/serverless client.
