### ISSUE TITLE
[Bug] Creating vector indexes for MongoDB Atlas assumes data is stored in pascal casing

### ISSUE THREAD

**Issue by walexee** [microsoft/kernel-memory#758]
### Context / Scenario

If **CamelCaseElementNameConvention** is enabled, data fields are stored in the collections in camel case despite what the property names are. However, the current implementation has index field references targeting field names in Pascal casing. This breaks the vector definition because it's targeting fields that do not exist.

### What happened?

Our data is stored as:

```Json
{
  "index": "default",
  "embedding": [],  
  "tags": [
    { 
      "key": "", 
      "values": "" 
    }
  ]
}
```

But the index was created as:

```Json
"fields": [
  {
    "numDimensions": 1536,
    "path": "Embedding",
    "similarity": "cosine",
    "type": "vector"
  },
  {
    "path": "Index",
    "type": "filter"
  },
 {
    "path": "Tags.Key",
    "type": "filter"
  },
 {
    "path": "Tags.Values",
    "type": "filter"
  }
]

```

### Importance

a fix would make my life easier

### Platform, Language, Versions

C#
NET 8.0
Microsoft.KernelMemory.MongoDbAtlas@0.71.240820.1
MongoDB Atlas

### Relevant log output

```shell
Command aggregate failed: PlainExecutor error during aggregation :: caused by :: embedding is not indexed as vector.
```

**Comment by dluc** [comment]
help is welcome if someone can look into this. Perhaps this is one of those problems that will be addressed once we've migrated to the new SK memory classes (end of 2024).

**Comment by walexee** [comment]
I can address the issue. I found out from the code that the names of the
targeted fields are hard-coded. I can change that.
How can I submit a PR?

Thanks,
Wale

**Comment by dluc** [comment]
> How can I submit a PR? Thanks, Wale

@walexee the process is described here https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request - usually that involves:

- fork KM repo, which will generate a new repo under your user, e.g. https://github.com/walexee/kernel-memory
- check out the repo on your local machine
- create a new branch, e.g. "git checkout -b fix758"
- make the code changes locally on your machine, plus tests
- commit changes
- push changes to GitHub (ie push the new branch to your fork)
- create pull request - this link might work https://github.com/microsoft/kernel-memory/compare/main...walexee:kernel-memory:fix758 - otherwise see the docs

**Comment by walexee** [comment]
Thanks Devis. I'll submit a PR ASAP.

**Comment by dluc** [comment]
Fixed - https://github.com/microsoft/kernel-memory/pull/762
