### ISSUE TITLE
[Bug] In Azure AI Search Index, the embedding field is not marked as 'Retrievable'

### ISSUE THREAD

**Issue by bancroftway** [microsoft/kernel-memory#809]
### Context / Scenario

I have checked my older projects where I used KM, and the embedding field in Azure AI Search index used to be retrievable in the index that was created by KM. However, this field is no longer being marked as retrievable by default. I have to manually turn this flag on in Azure portal.

![image](https://github.com/user-attachments/assets/e9678470-d170-4729-9b1a-7593125d604d)

### What happened?

Embedding field in Azure AI Search index is not marked as Retrievable.

### Importance

edge case

### Platform, Language, Versions

.Net 9. KM version 0.75.240924.1

**Comment by dluc** [comment]
The index schema is more of an internal implementation detail, so I wouldn’t classify this as a bug. Since KM doesn’t require the “retrievability” flag for generating search results and answers, it’s not set by default. However, if you’re using the indexes for other applications, it’s totally fine to update the flag manually as you’ve done.
