### ISSUE TITLE
How to update documents/embeddings stored in a vector database using semantic memory?

### ISSUE THREAD

**Issue by jcreek** [microsoft/kernel-memory#85]
I've had a look through and it's not clear what the intended workflow is for this scenario. Say I've ingested a number of documents, but one has been updated, how would I go about updating the memory?

**Comment by dluc** [comment]
hi @jcreek you should be able to achieve what you suggest simply by uploading with the same Document ID.  If you put multiple files under the same ID you will have to upload all of them, otherwise, those missing will be considered deletions. Typically you might want to have one-file-one-document-ID, to keep things simple.  
One idea: if you don't want to persist document IDs, you can generate consistent one "hashing" the original file path+name (or URL), something like:  Document ID = SHA256(lowercase(full file path))
